#!/bin/bash
read -p "The file name is: " file
echo "#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/**
 * main - Entry point
 *
 * Description:
 *
 * Return: 0 means no errors.
*/

int main(void)
{
	
	return (0);
}" >> $file
nano $file
