#!/bin/bash
read -p "The file name is: " file
echo "#include <stdio.h>

/**
 * main - Entry point
 *
 * Description:
 *
 * Return: 0 means no errors.
*/

int main(void)
{
    
    return 0;
}" >> $file.c
nano $file.c
if [ -f $file.c.c ]; then
    mv $file.c.c $file.c
fi
